A small improvement
cheeezburga/skript-pattern-parser pull request #3
Opened 2024-11-17 21:49 UTC by JonesJugHead

# Lore update :
- Addition of a preview for saved lores
- Addition of a delete button for saved lores
- Disable spell check on input
![image](https://github.com/user-attachments/assets/ac140e6d-950d-4eb3-bdbb-8cb29de4baad)

2024-11-18 04:30 UTC, cheeezburga commented
This looks like a really nice addition, thanks for the PR! I'll just do some testing with it when I get home before I merge it 👍

2024-11-18 04:30 UTC, cheeezburga approved these changes

2024-11-19 07:55 UTC, cheeezburga requested changes
Did some quick testing and I seem to get this whenever there's only 1 line:
![image](https://github.com/user-attachments/assets/af183a12-e555-4dfa-ad9c-902d558aac26)

Also, just some other small notes:
* Would rather comments are left out, I'm planning on going through everything and adding comments later on
* If you wouldn't mind using `'` instead of `"`

2024-11-19 08:22 UTC, JonesJugHead commented
Here it is, I've updated it.

I admit that my Prettier (https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) wants to fix a lot of things
(Tab to space, `"` to `'`, etc., but there is no configuration file in the project, so I don't know the standards to follow. It would be good to add a Prettier configuration file and format all the files accordingly).

Regarding the buttons, I admit that the way you've done them isn't extremely good. If you want, we can merge the PR, and later in the evening (GMT +1 timezone), I'll submit a PR where I fix your HTML a bit and the way things work (HTML & CSS).

2024-11-19 09:01 UTC, cheeezburga requested changes

2024-11-19 09:01 UTC, cheeezburga commented on lore-generator/script.js
> +		const formattedLines = loreLines.map(line => `'${line.replace(/'/g, '''')}'`);
This is actually changing the functionality

2024-11-19 09:06 UTC, cheeezburga commented
> Here it is, I've updated it.
> 
> I admit that my Prettier (https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) wants to fix a lot of things (Tab to space, `"` to `'`, etc., but there is no configuration file in the project, so I don't know the standards to follow. It would be good to add a Prettier configuration file and format all the files accordingly).
> 
> Regarding the buttons, I admit that the way you've done them isn't extremely good. If you want, we can merge the PR, and later in the evening (GMT +1 timezone), I'll submit a PR where I fix your HTML a bit and the way things work (HTML & CSS).

I'll look into making a Prettier config, wasnt aware of that extension. At the very least, I'll make a readme and include some of the basic styling stuff in there. And I think I'd rather merge a fully working version rather than two PRs, so if you want to just include any further changes in this one, feel free!

2024-11-19 09:27 UTC, JonesJugHead commented
Alright, I'll look into it then.
But yes, Prettier would be really cool, especially when we're collaborating.
Could you also add to the readme that using Prettier is recommended?

2024-11-19 12:41 UTC, cheeezburga commented
> Alright, I'll look into it then. But yes, Prettier would be really cool, especially when we're collaborating. Could you also add to the readme that using Prettier is recommended?

I've added a Prettier config file, and updated all files so far to use it 👍

2024-12-22 18:04 UTC, JonesJugHead commented
@cheeezburga updated (sorry for the delay)

2025-04-07 07:50 UTC, JonesJugHead commented
up @cheeezburga

2025-05-19 17:56 UTC, closed without merging